# Generated by Django 4.2.6 on 2024-12-24 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(choices=[('Cardiologie', 'Cardiologie'), ('Dermatologie', 'Dermatologie'), ('Pédiatrie', 'Pédiatrie'), ('Orthopédie', 'Orthopédie'), ('Psychiatrie', 'Psychiatrie'), ('Gynécologie', 'Gynécologie')], default='Cardiologie', max_length=30)),
                ('numero_telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelAdministratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('poste', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('numero_securite_sociale', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('mutuelle', models.CharField(blank=True, max_length=255, null=True)),
                ('personne_contact_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('personne_contact_telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('medecin_traitant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Med_Patient.medecin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DossierPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_derniere_mise_a_jour', models.DateField(auto_now=True)),
                ('NSS', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Med_Patient.patient')),
            ],
        ),
    ]
