# Generated by Django 4.2.6 on 2024-12-25 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Med_Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateField()),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('resume', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dossierpatient',
            name='antecedents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordonnance', models.DateField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='Med_Patient.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=50)),
                ('frequence', models.CharField(max_length=50)),
                ('duree', models.CharField(max_length=50)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicament_ordonnances', to='Med_Patient.medicament')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicament_ordonnances', to='Med_Patient.ordonnance')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(choices=[('biologique', 'Biologique'), ('radiologique', 'Radiologique')], max_length=20)),
                ('date_examen', models.DateField()),
                ('bilan', models.TextField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='Med_Patient.consultation')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='dossier_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='Med_Patient.dossierpatient'),
        ),
    ]
