# Generated by Django 4.2.6 on 2024-12-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Med_Patient', '0002_consultation_medicament_dossierpatient_antecedents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossierpatient',
            name='antecedents',
        ),
        migrations.AddField(
            model_name='consultation',
            name='antecedents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
