# Generated by Django 4.2.6 on 2024-12-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Med_Patient', '0003_remove_dossierpatient_antecedents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='Med_Patient.medecin'),
        ),
    ]
