# Generated by Django 4.2.6 on 2024-12-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Med_Patient', '0004_consultation_medecin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='antecedents',
        ),
        migrations.AddField(
            model_name='dossierpatient',
            name='antecedents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
