# Generated by Django 4.2.6 on 2024-12-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Med_Patient', '0005_remove_consultation_antecedents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
