# Generated by Django 4.2.6 on 2024-12-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Med_Patient', '0006_ordonnance_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='est_validee',
            field=models.BooleanField(default=False, help_text="Indique si l'ordonnance a été validée par le médecin", verbose_name='Ordonnance validée'),
        ),
    ]
