# Generated by Django 4.2.6 on 2024-12-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soins_Exams_Patient', '0002_soin'),
        ('Med_Patient', '0007_ordonnance_est_validee'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='soin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicaments', to='Soins_Exams_Patient.soin'),
        ),
    ]
