# Generated by Django 4.2.6 on 2024-12-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Med_Patient', '0008_medicament_soin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
