# Generated by Django 4.2.6 on 2024-12-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Med_Patient', '0007_ordonnance_est_validee'),
        ('Soins_Exams_Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soin', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('dossier_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='Med_Patient.dossierpatient')),
                ('infirmier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='Soins_Exams_Patient.infirmier')),
            ],
        ),
    ]
