# Generated by Django 4.2.6 on 2024-12-28 19:53

import Soins_Exams_Patient.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Med_Patient', '0009_alter_medicament_nom'),
        ('Soins_Exams_Patient', '0002_soin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LaborantainRadiologue',
            new_name='LaborantinRadiologue',
        ),
        migrations.CreateModel(
            name='ResultatExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glycemie', models.CharField(max_length=10, verbose_name='glycemie')),
                ('hypertension', models.CharField(max_length=10, verbose_name='hypertension')),
                ('fer', models.CharField(max_length=10, verbose_name='fer')),
                ('TSH', models.CharField(max_length=10, verbose_name='TSH')),
                ('cholesterol', models.CharField(max_length=10, verbose_name='cholesterol')),
                ('compte_rendu', models.TextField(help_text="Compte rendu détaillé de l'examen", verbose_name='Compte rendu')),
                ('image_medicale', models.ImageField(help_text='Image médicale au format JPG, PNG ou DICOM', upload_to='examens/images/', validators=[Soins_Exams_Patient.models.validate_medical_image], verbose_name='Image médicale')),
                ('examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='Med_Patient.examen')),
                ('laborantin_radiologue', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resultats_examens', to='Soins_Exams_Patient.laborantinradiologue')),
            ],
        ),
    ]
