# Generated by Django 4.2.6 on 2024-12-30 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Soins_Exams_Patient', '0003_rename_laborantainradiologue_laborantinradiologue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborantinradiologue',
            name='role',
            field=models.CharField(choices=[('Laborantin', 'Laborantin'), ('Radiologue', 'Radiologue')], max_length=20),
        ),
        migrations.AlterField(
            model_name='laborantinradiologue',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laborantin_radiologue', to=settings.AUTH_USER_MODEL),
        ),
    ]
