# Generated by Django 4.2.6 on 2024-12-30 11:41

import Soins_Exams_Patient.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soins_Exams_Patient', '0004_alter_laborantinradiologue_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultatexamen',
            name='TSH',
            field=models.CharField(max_length=10, null=True, verbose_name='TSH'),
        ),
        migrations.AlterField(
            model_name='resultatexamen',
            name='cholesterol',
            field=models.CharField(max_length=10, null=True, verbose_name='cholesterol'),
        ),
        migrations.AlterField(
            model_name='resultatexamen',
            name='compte_rendu',
            field=models.TextField(blank=True, help_text="Compte rendu détaillé de l'examen", null=True, verbose_name='Compte rendu'),
        ),
        migrations.AlterField(
            model_name='resultatexamen',
            name='fer',
            field=models.CharField(max_length=10, null=True, verbose_name='fer'),
        ),
        migrations.AlterField(
            model_name='resultatexamen',
            name='glycemie',
            field=models.CharField(max_length=10, null=True, verbose_name='glycemie'),
        ),
        migrations.AlterField(
            model_name='resultatexamen',
            name='hypertension',
            field=models.CharField(max_length=10, null=True, verbose_name='hypertension'),
        ),
        migrations.AlterField(
            model_name='resultatexamen',
            name='image_medicale',
            field=models.ImageField(blank=True, help_text='Image médicale au format JPG, PNG ou DICOM', null=True, upload_to='examens/images/', validators=[Soins_Exams_Patient.models.validate_medical_image], verbose_name='Image médicale'),
        ),
    ]
