# Generated by Django 4.2.6 on 2024-12-30 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soins_Exams_Patient', '0005_alter_resultatexamen_tsh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultatexamen',
            name='laborantin_radiologue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Soins_Exams_Patient.laborantinradiologue'),
        ),
    ]
